########################################################################
#   .travis.yml

language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

env:
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=^8.7

notifications:
  email:
    recipients:
      - stefan.rotsch@aoe.com
    on_success: never
    on_failure: never

branches:
  only:
    - /^AOE_.*$/
    - /^issue\/.*$/
    - /^TYPO3.*$/

sudo: false

before_install:
  - composer self-update

before_script:
  # Enables us to test dev-master
  - composer config minimum-stability dev
  - composer config prefer-stable true
  # Installs nimut/typo3-complete
  - travis_wait 30 composer require --dev nimut/typo3-complete=$TYPO3_VERSION
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml
  - export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'
  # Locating FunctionalTests.xml
  - export "FUNCTIONAL_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml'
  # Symlink TYPO3-Core
  - ln -nfs .Build/vendor/typo3/cms/typo3 typo3

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit/
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/bin/phpunit --colors --process-isolation -c $FUNCTIONAL_XML Tests/Functional/
